    
title: Cashfree Engineering
description: >
   Cashfree integration kits for various platforms
   and programming languages.

permalink: /:title/
paginate: 16
paginate_path: /page:num/
markdown: kramdown

#social
facebook: http://facebook.com/gocashfree
twitter: http://twitter.com/@gocashfree
github: http://github.com/cashfree
email: techsupoort@gocashfree.com

# Sass style
sass:
  style: compressed

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
